[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'chain/=src/test/ethereum/',
    'ds-test/=lib/ds-test/src/',
    'openzeppelin/=lib/openzeppelin-contracts/contracts/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
