name: Fuse Leveraged Token
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.3.0"
      - run: npm i -g prettier solhint
      - run: prettier --check .
      - run: solhint "src/**/*.sol"
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: risedle/setup-dapptools@v4
        with:
          solc: "solc_0_8_11"
      - run: dapp update
      - run: dapp test --rpc -v
        env:
          DAPP_SOLC_VERSION: 0.8.11
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
          DAPP_REMAPPINGS: ""
