name: Fuse Leveraged Token Formatter
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.3.0"
          cache: "npm"
      - run: npm i -g prettier
      - run: prettier --check .
